[workspace]
members = [
  # tests and example code
  "examples",
  # the main library and tests
  "rustls",
  # example of custom provider
  "provider-example",
]
exclude = ["admin/rustfmt"]
resolver = "2"
